# Site settings
author: Anil Gurung
title: Why Software Engineering?
header-img: img/home-bg.png
email: anil_gurung15@yahoo.com
copyright_name: Anil Gurung
description: > # this means to ignore newlines until "baseurl:"
  Driving Force behind it
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Zatom01

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
